"""initial schema

Revision ID: e9655aea534d
Revises: 
Create Date: 2026-04-18 08:54:41.048035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e9655aea534d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('amazon_refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('amazon_marketplace_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('products',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('marketplace_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bsr_rank', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('review_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_asin'), 'products', ['asin'], unique=False)
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('user_marketplaces',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_id', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'marketplace_id', name='uq_user_marketplace')
    )
    op.create_index(op.f('ix_user_marketplaces_user_id'), 'user_marketplaces', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('amazon_campaign_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('targeting_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('daily_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_amazon_campaign_id'), 'campaigns', ['amazon_campaign_id'], unique=False)
    op.create_index(op.f('ix_campaigns_product_id'), 'campaigns', ['product_id'], unique=False)
    op.create_table('keywords',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('competition_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('suggested_bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_keywords_product_id'), 'keywords', ['product_id'], unique=False)
    op.create_table('listings',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('bullet_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('search_terms', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_product_id'), 'listings', ['product_id'], unique=False)
    op.create_table('campaign_keywords',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('keyword_text', sa.String(length=500), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_keywords_campaign_id'), 'campaign_keywords', ['campaign_id'], unique=False)
    op.create_table('keyword_rankings',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.Column('organic_rank', sa.Integer(), nullable=True),
    sa.Column('sponsored_rank', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_rankings_keyword_id'), 'keyword_rankings', ['keyword_id'], unique=False)
    op.create_table('listing_variants',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('bullet_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_variants_listing_id'), 'listing_variants', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_variants_listing_id'), table_name='listing_variants')
    op.drop_table('listing_variants')
    op.drop_index(op.f('ix_keyword_rankings_keyword_id'), table_name='keyword_rankings')
    op.drop_table('keyword_rankings')
    op.drop_index(op.f('ix_campaign_keywords_campaign_id'), table_name='campaign_keywords')
    op.drop_table('campaign_keywords')
    op.drop_index(op.f('ix_listings_product_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_keywords_product_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_campaigns_product_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_amazon_campaign_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_user_marketplaces_user_id'), table_name='user_marketplaces')
    op.drop_table('user_marketplaces')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_index(op.f('ix_products_asin'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
